version: '3'

services:
  app:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp:delegated

  db:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
